### ISSUE TITLE
Nova 10 causing darkened theme background

### ISSUE THREAD

**Issue by adammontague** [philbuchanan/Coda-Classic.novaextension#1]
The latest version of Nova (10) has altered the appearance of the Coda Classic theme, most notably the background colour of the editor is no longer white, but a mid-grey which makes text legibility poor.

![Screenshot 2022-10-28 at 14 09 44](https://user-images.githubusercontent.com/1705379/198600151-34ec9718-63a8-4312-8726-e1915926f6c8.png)

**Comment by philbuchanan** [comment]
This is a bug in Nova. The behaviour differs from what is outlined in their documentation. I have already filed a bug with them, but haven't received a response yet.
